<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>SkyWarsReloaded</artifactId>
        <groupId>com.walrusone</groupId>
        <version>${revision}</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>slime-asp</artifactId>

    <repositories>
        <repository>
            <id>papermc</id>
            <url>https://repo.papermc.io/repository/maven-public/</url>
        </repository>
        <repository>
            <id>minecraft-libraries</id>
            <name>Minecraft Libraries</name>
            <url>https://libraries.minecraft.net</url>
        </repository>

        <!-- InfernalSuite -->
        <repository>
            <id>is-releases</id>
            <url>https://repo.infernalsuite.com/repository/maven-releases/</url>
        </repository>
        <repository>
            <id>is-snapshots</id>
            <url>https://repo.infernalsuite.com/repository/maven-snapshots/</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>io.papermc.paper</groupId>
            <artifactId>paper-api</artifactId>
            <version>26.1.2.build.72-stable</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.walrusone</groupId>
            <artifactId>SkyWarsReloadedCore</artifactId>
            <version>${revision}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.jetbrains</groupId>
            <artifactId>annotations</artifactId>
            <version>26.1.0</version>
        </dependency>
        <dependency>
            <groupId>com.infernalsuite.asp</groupId>
            <artifactId>api</artifactId>
            <version>4.0.0-SNAPSHOT</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.infernalsuite.asp</groupId>
            <artifactId>file-loader</artifactId>
            <version>4.0.0-SNAPSHOT</version>
            <scope>compile</scope> <!-- cái này bắt buộc để compile do asp không đề cập đến file này trong jar của họ -->
        </dependency>
    </dependencies>
</project>